development: &non_production_settings
  site_domain: localhost:3000

test:
  <<: *non_production_settings

staging:
  site_domain: dev.crantastic.org

# TODO: Change this when crantastic.org points to Heroku
production:
  site_domain: dev.crantastic.org
