common: &common
    solr:
      hostname: localhost
      port: 8982

production:
  <<: *common
  solr:
    hostname: chrononaut.net
    port: 8080
    path: /solr

development:
  <<: *common

test:
  <<: *common
